version: '2.1'

services:
  app:
    build: ./app
    volumes:
      - ./app/.babelrc:/home/node/.babelrc
      - ./app/src:/home/node/src
      - ./app/start.js:/home/node/start.js
      - ./app/webpack.config.js:/home/node/webpack.config.js
      - ./app/static:/home/node/dist
    environment:
      - NODE_ENV=development
      - LOG_FORMAT=dev
      - SPA_BASE_URL=http://localhost:$APP_PORT
      - API_BASE_URL=http://localhost:$API_PORT
      - INTERNAL_API_BASE_URL=http://api:8000
    ports:
      - "$APP_PORT:8000"
    entrypoint: node start.js

